#pragma once
#include <iostream>
#include <vector>
#include <string>
#include <deque>
#include <cmath>
#include <map>
//#include "weapon.hpp"
#include "weapon.cpp"
//#include "personagem.hpp"
#include "personagem.cpp"
//#include "jogador.hpp"
#include "jogador.cpp"
//#include "inimigo.hpp"
#include "inimigo.cpp"
//#include "sala.hpp"
#include "sala.cpp"