#pragma once
#include <iostream>
#include <fstream>
#include <random>
#include <vector>
#include <string>
#include <deque>
#include <cmath>
#include <map>
std::knuth_b ran_num_gen(140601);
#include "nlohmann/json.hpp"
//#include "weapon.hpp"
#include "weapon.cpp"
//#include "personagem.hpp"
#include "personagem.cpp"
//#include "jogador.hpp"
#include "jogador.cpp"
//#include "inimigo.hpp"
#include "inimigo.cpp"
//#include "sala.hpp"
#include "sala.cpp"
//crypto++
#include "cryptlib.h"
#include "sha.h"//end
#include "persman.hpp"
#include "json_conversions.hpp"
