#pragma once
#include <iostream>
#include <string>
#include <deque>
#include <map>
#include "weapon.hpp"
#include "weapon.cpp"
#include "personagem.hpp"
#include "personagem.cpp"
#include "jogador.hpp"
#include "jogador.cpp"
#include "inimigo.hpp"
#include "inimigo.cpp"
#include "sala.hpp"
#include "sala.cpp"